### ISSUE TITLE
ToDo's

### ISSUE THREAD

**Issue by Luka-Kukoc** [Luka-Kukoc/dreamlife#2]
- [x] Create and implement a simple overall design 
- [ ] Setup unique id for each goal
- [x] Create auth0 test user
- [x] Remove signup option
- [ ] Publish to github pages
